# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "offensive-security/kali-linux"
    ## do not update vboxguest with the vagrant plugin
    ## vagrant-vbguest
    # config.vbguest.auto_update = false

    config.vm.hostname = "kali"
    config.vm.network "private_network", type: "dhcp"
    config.vm.synced_folder "/home/boogy", "/share"
    config.vm.boot_timeout = 600

    config.vm.provider "virtualbox" do |vb|
        vb.name = "kaliroling"
        vb.memory = 2048
        vb.cpus = 2
        vb.gui = false
    end

    config.vm.provision "shell", inline: <<-SHELL
    apt update
    apt install -y python python-pip python3 python3-pip mingw-w64 mingw-w32
    cd /home/vagrant/
    sudo -H -u vagrant git clone https://github.com/boogy/dotfiles
    sudo -H -u vagrant bash -c "echo y|/home/vagrant/dotfiles/install.sh" &>/dev/null
    SHELL
end
