$script = <<-SCRIPT
export DEBIAN_FRONTEND=noninteractive

dpkg --add-architecture i386
apt update
apt upgrade -y

apt -yq install libc6:i386 libc6-dev-i386 libncurses5:i386 libstdc++6:i386
apt -yq install software-properties-common apt-transport-https
apt -yq install python-dev python-pip python3-dev python3-pip python3-cryptography \
python-openssl python-virtualenv python-urllib3 virtualenvwrapper python-scapy

apt -yq install make cmake stunnel socat hydra p7zip rar unrar unzip strace \
ltrace bzip2 rdesktop whois samba-common samba-common-bin yasm nasm sslsplit

apt -yq install gdb gdb-multiarch gdbserver gcc gcc-multilib gcc-mingw-w64


## vagrant user

exec sudo -u vagrant /bin/bash - <<EOF
test -d dotfiles || git clone https://github.com/boogy/dotfiles
cd /home/vagrant/dotfiles && bash install.sh y

mkdir -p /home/vagrant/tools && cd $_
sudo -H -u vagrant pip2 install --upgrade --user r2pipe
sudo -H -u vagrant pip2 install --upgrade --user isort
sudo -H -u vagrant pip2 install --upgrade --user psutil
sudo -H -u vagrant pip2 install --upgrade --user requests
sudo -H -u vagrant pip2 install --upgrade --user pylint
sudo -H -u vagrant pip2 install --upgrade --user pexpect
sudo -H -u vagrant pip2 install --upgrade --user markdown
sudo -H -u vagrant pip2 install --upgrade --user pycrypto
sudo -H -u vagrant pip2 install --upgrade --user pwntools
sudo -H -u vagrant pip2 install --upgrade --user xortool
sudo -H -u vagrant pip2 install --upgrade --user scapy
sudo -H -u vagrant pip2 install --upgrade --user ecdsa

sudo -H -u vagrant pip3 install --upgrade --user requests
sudo -H -u vagrant pip3 install --upgrade --user pylint
sudo -H -u vagrant pip3 install --upgrade --user pexpect-u
sudo -H -u vagrant pip3 install --upgrade --user Pillow
sudo -H -u vagrant pip3 install --upgrade --user numpy
sudo -H -u vagrant pip3 install --upgrade --user pexpect
sudo -H -u vagrant pip3 install --upgrade --user capstone
sudo -H -u vagrant pip3 install --upgrade --user fierce
sudo -H -u vagrant pip3 install --upgrade --user selectors

cd /home/vagrant/tools

test -d peda      || git clone https://github.com/longld/peda.git
test -d pwndbg    || git clone https://github.com/pwndbg/pwndbg.git
test -d fierce    || git clone https://github.com/mschwager/fierce.git
test -d radare2   || git clone https://github.com/radare/radare2
test -d ROPgadget || git clone https://github.com/JonathanSalwan/ROPgadget \

EOF

chown -R vagrant:vagrant /home/vagrant

apt autoclean -y
apt autoremove -y
apt -y install -f

SCRIPT

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.hostname = "ubuntu1804"

    config.vm.provider "virtualbox" do |v|
        v.name = "ubuntu1804"
        v.memory = 2048
        v.cpus = 2
    end

    # config.vm.provision "shell", path: "script.sh"
    config.vm.provision "shell", inline: $script

    config.vm.synced_folder "/home/boogy", "/home/vagrant/share/"
end
