#!/usr/bin/env bash

bspc rule -r "*"

## Set environment
export BSPWM_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/bspwm"

##
## BSPWM configuration
##

## longest_side || alternate || spiral
bspc config automatic_scheme              longest_side
#bspc config border_radius                8
bspc config border_width                  1
bspc config window_gap                    4
bspc config top_padding                   0
bspc config bottom_padding                18
bspc config left_padding                  0
bspc config right_padding                 0
## monocle mode for single windows
bspc config single_monocle                true
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config pointer_follows_focus         true
bspc config pointer_follows_monitor       true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config remove_unplugged_monitors     true
bspc config merge_overlapping_monitors    true
bspc config center_pseudo_tiled           true
## Ignore EWMH focus requests coming from applications
bspc config ignore_ewmh_focus             false
## commnands: xmodmap -pke | xmodmap -pm
## shift, control, lock, mod1, mod2, mod3, mod4, mod5
## mod1=Alt, mod4=super, mod5=AltGr
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

##
## BSPWM Colors
##
# bspc config focused_border_color	      "#5e81ac"
bspc config normal_border_color		      "#4c566a"
bspc config active_border_color	          "#1e1e1e"
bspc config focused_border_color	      "#00ff00"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"

##
## BSPWM monitors
##
"$BSPWM_CONFIG/scripts/setup-monitors.sh" &

## Use monocle layout on desktop 1
# bspc desktop '^1' --layout monocle

# Make windows float on specific desktops
# https://github.com/baskerville/bspwm/issues/325
# bspc subscribe node_manage | while read event monitor desktop nodeid ipid; do
#     case "$desktop" in
#         www|play|6|virt|7|9)
#             bspc node "$nodeid" --state floating
#             ;;
#     esac
# done &

## Script for external rules
bspc config external_rules_command "$BSPWM_CONFIG/scripts/external-rules.sh"

## Send to desktop
bspc rule --add Libreoffice               desktop='6'  follow=on  monitor=focused
bspc rule --add '*:soffice' state=tiled   desktop='6'  follow=on  monitor=focused
bspc rule --add Hexchat                   desktop='10' follow=on  monitor=focused
bspc rule --add Xchat                     desktop='10' follow=on  monitor=focused
bspc rule --add Vmware                    desktop='5'  follow=on  monitor=focused

## Other floating windows
bspc rule --add Blueman-manager         state=floating
bspc rule --add Shutter                 state=floating
bspc rule --add Solaar                  state=floating
bspc rule --add Arandr                  state=floating
bspc rule --add Display                 state=floating
bspc rule --add Empathy                 state=floating
bspc rule --add Eog                     state=floating
bspc rule --add feh                     state=floating
bspc rule --add KeePassXC               state=floating
bspc rule --add mpv                     state=floating
bspc rule --add Nautilus                state=floating
bspc rule --add Pavucontrol             state=floating
bspc rule --add Remmina                 state=floating
bspc rule --add "Syncthing GTK"         state=floating
bspc rule --add Transmission-gt         state=floating

## Load session
. "$BSPWM_CONFIG/restore.cfg"
if [ -e "$BSPWM_STATE" ] ; then
    bspc wm --load-state "$BSPWM_STATE"
    bspc wm --adopt-orphans
    rm "$BSPWM_STATE"
fi

##
## AUTOSTART
##
"$BSPWM_CONFIG/scripts/autostart.sh" &
