#!/usr/bin/env bash

OUTPUT1="eDP1"
OUTPUT2="DP2-1"
OUTPUT3="DP1-2"

if [ "$1" = "work" ]; then
    bash ~/.screenlayout/work.sh
fi

if [ "$1" = "laptop" ]; then
    bash ~/.screenlayout/laptop.sh
fi

if [ "$1" = "home" ]; then
    bash ~/.screenlayout/home.sh
fi
